#pragma once

// Serial USART duplex.
//#define SERIAL_USART_FULL_DUPLEX   // Enable full duplex operation mode.
//#define SERIAL_USART_TX_PIN GP0    // USART TX pin
//#define SERIAL_USART_RX_PIN GP1    // USART RX pin

//#define SOFT_SERIAL_PIN GP1
//#define PAL_USE_CALLBACKS TRUE
#define SERIAL_PIO_USE_PIO1
#define SERIAL_USART_TX_PIN GP27

// Reset.
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP16
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U